version: '2'
services:
    waf:
        build: waf
        hostname: ngnix-security
        restart: always
        ports:
            - 8443:8443
        environment:
            - SEC_RULE_ENGINE=On
            - HTTP_VERSION=1.1
            - DOMAIN=testphp.vulnweb.com
            - TARGET_PORT=80
            - TARGET_HOST=testphp.vulnweb.com
            - CLIENT_MAX_BODY_SIZE=200M
            - SSL_PORT=8443
        volumes: ['nginx-certs:/usr/local/nginx/certs']
volumes: {"nginx-certs"}