version: '2'
services:
    waf:
        build: waf
        ports:
            - "8443:8443"
        environment:
            - SEC_RULE_ENGINE=On
            - HTTP_VERSION=1.1
            - DOMAIN=localhost
            - TARGET_PORT=1234
            - TARGET_HOST=localhost
            - CLIENT_MAX_BODY_SIZE=200M
            - SSL_PORT=8443

            